### ISSUE TITLE
does not work with ocamlnet 4.0.1

### ISSUE THREAD

**Issue by romerun** [darioteixeira/ocaml-bitcoin#4]
looks like ocamlnet 4.0.1, released on opam recently, has changed some interfaces

**Comment by darioteixeira** [comment]
Yes, it seems like a relatively trivial change: Http_client has been renamed to Nethttp_client.
I intend to push a new version out soon anyway, and I'll incorporate this fix.  In the meantime I've updated the constraints on the OPAM package.

**Comment by darioteixeira** [comment]
Now fixed in master, which was also brought up-to-date with the latest Bitcoin Core release.
