### ISSUE TITLE
OPAM release ?

### ISSUE THREAD

**Issue by vbmithr** [darioteixeira/ocaml-bitcoin#6]
Would be nice.

**Comment by darioteixeira** [comment]
I've been waiting to hear from a member of the Bitcoin Core team regarding the proper annotation of the types of the official API (which right now is very stringly-typed and somewhat inconsistent).  But yeah, it's taking a long time, so I might as well release now (I'll do so tomorrow).

**Comment by vbmithr** [comment]
On 18/07/2015 20:57, Dario Teixeira wrote:
> I've been waiting to hear from a member of the Bitcoin Core team
> regarding the proper annotation of the types of the official API (which
> right now is very stringly-typed and somewhat inconsistent). But yeah,
> it's taking a long time, so I might as well release now (I'll do so
> tomorrow).
> 

Great, thanks!

**Comment by darioteixeira** [comment]
New version is out and [PR](https://github.com/ocaml/opam-repository/pull/4502) already submitted to `opam-repository`...
